# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3763447a5adcc55e7b61de9ebe45038597f724d53cd9b8d6ec7c7779b969b883899793ce2f82c1027806c1f79ae15e8f4777f088a6c954a1251a53038aa354e3

test:
  secret_key_base: 11fed7c36d29d2ede4acf431a593531a0832421bc60d25e1505d272b6061c08b38057e01e2c7fd7a6046cc77f8ab902e6d9c97fb3c6ffbd01be36f3f1e3a37df

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
